### ISSUE TITLE
"CSS for PyInstaller Documentation"?

### ISSUE THREAD

**Issue by htgoebel** [bjones1/CodeChat#11]
CodeChat/CodeChat/template/default.css  says: "CSS for PyInstaller Documentation". I assume, this is no longer correct :-)

But I wonder whether one should include this stylesheet when using  CodeChat.

**Comment by bjones1** [comment]
Oops. That should indicate that this file was copied from (not for) PyInstaller's documentation. I'll update this.

**Comment by bjones1** [comment]
Fixed in 73bccc870c4d83fe6e3d8d713ee7a6ded31c3133.
