### ISSUE TITLE
Code included with codeinclude should be a block

### ISSUE THREAD

**Issue by htgoebel** [bjones1/CodeChat#13]
When including a file using 
```
.. codeinclude: some-file.yml
```
the generated HTML is just is list of HTML elements. I'd like to have these wrapped in a `<div class="codechat">` so I can select styles for these, e.g. a margin below the whole block.

**Comment by bjones1** [comment]
Hmmm. This is non-trivial. I'll think on it.

**Comment by bjones1** [comment]
I've added support for the `class` option in 9b6d3c654f80661b1f0a283722928c89ad60d051. To use this:

``` rest
.. codeinclude:: some-file.yml
    :class: snazzy
```
