### ISSUE TITLE
Elements contain element styles

### ISSUE THREAD

**Issue by htgoebel** [bjones1/CodeChat#14]
Within a HTML document generated by CodeChat, many elements contain element styles like `maring-bottom:0`.

I'd like to have CSS calsses here, so I could address the style from the Stylesheet.

**Comment by bjones1** [comment]
Good point. Done in 3a3a2dc3a1446248d51952aad7d38617c70f4235.

**Comment by htgoebel** [comment]
Thanks for fixing all my issues so quick :-)

**Comment by bjones1** [comment]
My pleasure! I'm excited that you're using CodeChat.
