### ISSUE TITLE
Documentation issues - missing directory

### ISSUE THREAD

**Issue by rojalator** [bjones1/CodeChat#15]
The tutorial.rst file states that there shoud be a "sphinx_template" directory, but no such directory exists.

**Comment by bjones1** [comment]
Thanks for pointing this out -- I'll update the docs. The CodeChat System now stores [templates](https://codechat-system.readthedocs.io/en/latest/CodeChat_Server/install.html#templates), and also provides support for a wider variety of renderers; it supports Sphinx, mdbook, mkdocs, etc.

**Comment by rojalator** [comment]
OK, I'll keep trying...

**Comment by bjones1** [comment]
Fixed now.
