### ISSUE TITLE
Paths not passed correctly to Sphinx

### ISSUE THREAD

**Issue by rojalator** [bjones1/CodeChat#18]
(see also issue #17)

assuming:

/home/xxx/some_project/docs is the directory containing the yaml file and sphinx's conf.py is in source/ below that with output to build/ in the docs/ directory. Thus:
`
/home/xxx/some_project

--/python_code/
--/docs/
----/source/
----/build/
`

Setting source_path to `../python_code` and `output_path` to `_chat_build` in `codechat_config.yaml`, with -c set to `-csource` and running from `docs/`, CodeChat_server build fails with:

> Sphinx error:
root file /home/xxx/some_project/python_code/index.rst not found
/home/xxx/some_project/docs:: ERROR: unable to compute path relative to /home/xxx/some_project/docs/../python_code. 
'/home/xxx/some_project/docs' is not in the subpath of '/home/xxx/some_project/docs/../python_code' OR one path is relative and the other is absolute.
/home/xxx/some_project/docs:: ERROR: CodeChat renderer - unable to find the HTML output file /home/xxx/some_project/docs/_chat_build.
The rendered result is stored in /home/xxx/some_project/docs/_chat_build.

index.rst (and conf.py) are in docs/source.

**Comment by bjones1** [comment]
Answered in #17.
