### ISSUE TITLE
Some broken links to https://codechat.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by bwoodsend** [bjones1/CodeChat#19]
https://codechat.readthedocs.io/en/latest/ appears to no longer exist in favour of https://codechat.readthedocs.io/en/master/. This leaves a couple of broken links in the readme. Not sure if you'd want the links updated or the readthedocs config adjusted?

**Comment by bjones1** [comment]
Thanks! I turned https://codechat.readthedocs.io/en/latest/ back on.
